main: thirtyvirus.template.Swapper
version: 1.0
name: Swapper
api-version: 1.13

commands:
  swapper:
    description: Main command for Swapper. Use /template help for more info
permissions:
  swapper.user:
    description: Allows player to use the plugin's user features
    default: true
  swapper.admin:
    description: Allows player to use the plugin's admin features
    default: op